/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResultRouteImport } from './routes/result'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as DevComponentsRouteImport } from './routes/dev/components'
import { Route as SamplesSampleIdRouteImport } from './routes/samples/$sampleId'
import { Route as AuthProviderCallbackRouteImport } from './routes/auth/$provider/callback'
import { Route as SamplesSampleIdReviewRouteImport } from './routes/samples/$sampleId_.review'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultRoute = ResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DevComponentsRoute = DevComponentsRouteImport.update({
  id: '/dev/components',
  path: '/dev/components',
  getParentRoute: () => rootRouteImport,
} as any)
const SamplesSampleIdRoute = SamplesSampleIdRouteImport.update({
  id: '/samples/$sampleId',
  path: '/samples/$sampleId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthProviderCallbackRoute = AuthProviderCallbackRouteImport.update({
  id: '/auth/$provider/callback',
  path: '/auth/$provider/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const SamplesSampleIdReviewRoute = SamplesSampleIdReviewRouteImport.update({
  id: '/samples/$sampleId_/review',
  path: '/samples/$sampleId/review',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/result': typeof ResultRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/dev/components': typeof DevComponentsRoute
  '/samples/$sampleId': typeof SamplesSampleIdRoute
  '/auth/$provider/callback': typeof AuthProviderCallbackRoute
  '/samples/$sampleId/review': typeof SamplesSampleIdReviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/result': typeof ResultRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/dev/components': typeof DevComponentsRoute
  '/samples/$sampleId': typeof SamplesSampleIdRoute
  '/auth/$provider/callback': typeof AuthProviderCallbackRoute
  '/samples/$sampleId/review': typeof SamplesSampleIdReviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/result': typeof ResultRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/dev/components': typeof DevComponentsRoute
  '/samples/$sampleId': typeof SamplesSampleIdRoute
  '/auth/$provider/callback': typeof AuthProviderCallbackRoute
  '/samples/$sampleId_/review': typeof SamplesSampleIdReviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/result'
    | '/review'
    | '/settings'
    | '/dev/components'
    | '/samples/$sampleId'
    | '/auth/$provider/callback'
    | '/samples/$sampleId/review'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/result'
    | '/review'
    | '/settings'
    | '/dev/components'
    | '/samples/$sampleId'
    | '/auth/$provider/callback'
    | '/samples/$sampleId/review'
  id:
    | '__root__'
    | '/'
    | '/privacy'
    | '/result'
    | '/review'
    | '/settings'
    | '/dev/components'
    | '/samples/$sampleId'
    | '/auth/$provider/callback'
    | '/samples/$sampleId_/review'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyRoute: typeof PrivacyRoute
  ResultRoute: typeof ResultRoute
  ReviewRoute: typeof ReviewRoute
  SettingsRoute: typeof SettingsRoute
  DevComponentsRoute: typeof DevComponentsRoute
  SamplesSampleIdRoute: typeof SamplesSampleIdRoute
  AuthProviderCallbackRoute: typeof AuthProviderCallbackRoute
  SamplesSampleIdReviewRoute: typeof SamplesSampleIdReviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result': {
      id: '/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/components': {
      id: '/dev/components'
      path: '/dev/components'
      fullPath: '/dev/components'
      preLoaderRoute: typeof DevComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/samples/$sampleId': {
      id: '/samples/$sampleId'
      path: '/samples/$sampleId'
      fullPath: '/samples/$sampleId'
      preLoaderRoute: typeof SamplesSampleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$provider/callback': {
      id: '/auth/$provider/callback'
      path: '/auth/$provider/callback'
      fullPath: '/auth/$provider/callback'
      preLoaderRoute: typeof AuthProviderCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/samples/$sampleId_/review': {
      id: '/samples/$sampleId_/review'
      path: '/samples/$sampleId/review'
      fullPath: '/samples/$sampleId/review'
      preLoaderRoute: typeof SamplesSampleIdReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyRoute: PrivacyRoute,
  ResultRoute: ResultRoute,
  ReviewRoute: ReviewRoute,
  SettingsRoute: SettingsRoute,
  DevComponentsRoute: DevComponentsRoute,
  SamplesSampleIdRoute: SamplesSampleIdRoute,
  AuthProviderCallbackRoute: AuthProviderCallbackRoute,
  SamplesSampleIdReviewRoute: SamplesSampleIdReviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
