/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResultRouteImport } from './routes/result'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as CaptureIndexRouteImport } from './routes/capture/index'
import { Route as CaptureReviewRouteImport } from './routes/capture/review'
import { Route as DevComponentsRouteImport } from './routes/dev/components'
import { Route as SamplesSampleIdRouteImport } from './routes/samples/$sampleId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultRoute = ResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptureIndexRoute = CaptureIndexRouteImport.update({
  id: '/capture/',
  path: '/capture/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptureReviewRoute = CaptureReviewRouteImport.update({
  id: '/capture/review',
  path: '/capture/review',
  getParentRoute: () => rootRouteImport,
} as any)
const DevComponentsRoute = DevComponentsRouteImport.update({
  id: '/dev/components',
  path: '/dev/components',
  getParentRoute: () => rootRouteImport,
} as any)
const SamplesSampleIdRoute = SamplesSampleIdRouteImport.update({
  id: '/samples/$sampleId',
  path: '/samples/$sampleId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/result': typeof ResultRoute
  '/settings': typeof SettingsRoute
  '/capture/review': typeof CaptureReviewRoute
  '/dev/components': typeof DevComponentsRoute
  '/samples/$sampleId': typeof SamplesSampleIdRoute
  '/capture/': typeof CaptureIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/result': typeof ResultRoute
  '/settings': typeof SettingsRoute
  '/capture/review': typeof CaptureReviewRoute
  '/dev/components': typeof DevComponentsRoute
  '/samples/$sampleId': typeof SamplesSampleIdRoute
  '/capture': typeof CaptureIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/result': typeof ResultRoute
  '/settings': typeof SettingsRoute
  '/capture/review': typeof CaptureReviewRoute
  '/dev/components': typeof DevComponentsRoute
  '/samples/$sampleId': typeof SamplesSampleIdRoute
  '/capture/': typeof CaptureIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/result'
    | '/settings'
    | '/capture/review'
    | '/dev/components'
    | '/samples/$sampleId'
    | '/capture/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/result'
    | '/settings'
    | '/capture/review'
    | '/dev/components'
    | '/samples/$sampleId'
    | '/capture'
  id:
    | '__root__'
    | '/'
    | '/result'
    | '/settings'
    | '/capture/review'
    | '/dev/components'
    | '/samples/$sampleId'
    | '/capture/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ResultRoute: typeof ResultRoute
  SettingsRoute: typeof SettingsRoute
  CaptureReviewRoute: typeof CaptureReviewRoute
  DevComponentsRoute: typeof DevComponentsRoute
  SamplesSampleIdRoute: typeof SamplesSampleIdRoute
  CaptureIndexRoute: typeof CaptureIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result': {
      id: '/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capture/': {
      id: '/capture/'
      path: '/capture'
      fullPath: '/capture/'
      preLoaderRoute: typeof CaptureIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capture/review': {
      id: '/capture/review'
      path: '/capture/review'
      fullPath: '/capture/review'
      preLoaderRoute: typeof CaptureReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/components': {
      id: '/dev/components'
      path: '/dev/components'
      fullPath: '/dev/components'
      preLoaderRoute: typeof DevComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/samples/$sampleId': {
      id: '/samples/$sampleId'
      path: '/samples/$sampleId'
      fullPath: '/samples/$sampleId'
      preLoaderRoute: typeof SamplesSampleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ResultRoute: ResultRoute,
  SettingsRoute: SettingsRoute,
  CaptureReviewRoute: CaptureReviewRoute,
  DevComponentsRoute: DevComponentsRoute,
  SamplesSampleIdRoute: SamplesSampleIdRoute,
  CaptureIndexRoute: CaptureIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
